### ISSUE TITLE
Yamaha WXC-50

### ISSUE THREAD

**Issue by Hasifant** [coop-git/YamahaMusicCast#1]
I see, you just started this binding project, but would it be possible to also include „Tidal“ as choice for input source - I would give it a try with my Yamaha WXC-50 network player.

**Comment by coop-git** [comment]
Hi, I copied the options for _Input_ from the documentation and _Tidal_ is not in there. In the meantime, I have found a second version of this document and there _Tidal_ is mentioned.
If your device is having the latest firmware, you should be able to use Tidal as Input. The value should be tidal in lower case.
I will update the documentation to mention the difference between v1 and v2 of the API.
You can give it a try and let me know.

FYI : Discussion of this binding is currently done via [OpenHAB community](https://community.openhab.org/t/yamaha-musiccast-binding-revival/57833). Might be interesting to follow what is going on.

**Comment by Hasifant** [comment]
Hi,
great, thank you for your fast response!

I’ve tested my Yamaha WXC-50 now – integration with OH2.5 works.
Tested so far: power switching, source selection (including „tidal“)

Best regards

Von: coop-git <notifications@github.com>
Gesendet: Mittwoch, 4. November 2020 11:16
An: coop-git/YamahaMusicCast <YamahaMusicCast@noreply.github.com>
Cc: Endurofahrer <hasifant@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [coop-git/YamahaMusicCast] Yamaha WXC-50 (#1)


Hi, I copied the options for Input from the documentation and Tidal is not in there. In the meantime, I have found a second version of this document and there Tidal is mentioned.
If your device is having the latest firmware, you should be able to use Tidal as Input. The value should be tidal in lower case.
I will update the documentation to mention the difference between v1 and v2 of the API.
You can give it a try and let me know.

FYI : Discussion of this binding is currently done via OpenHAB communicty<https://community.openhab.org/t/yamaha-musiccast-binding-revival/57833>. Might be interesting to follow what is going on.

**Comment by coop-git** [comment]
OK, thx for the feedback. Update will follow soon, need to commit changes.
