### ISSUE TITLE
Please provide build jar OH3

### ISSUE THREAD

**Issue by xasz** [coop-git/YamahaMusicCast#6]
Hello,

i would love to help you test your addon.
I switch from OH2 to OH3 and i have some old musiccast jar what i found in some forum some time again.
It worked pretty good but seems not to work with OH3 anymore.

If you provide me a jar of your addon, i would like to test it :)

**Comment by coop-git** [comment]
There is a compiled JAR for OH2.5 and OH3.
You find them [here](https://github.com/coop-git/YamahaMusicCast/tree/master/target)

**Comment by xasz** [comment]
Well thanks, i am sorry. How blind am i ? :)
